version: '3.18'

services:
  coredns:
    build:
      dockerfile: docker/coredns.Dockerfile
      context: .
    image: koh/sv-coredns
    container_name: sv-coredns
    ports:
      - "853:53/udp" # testing DNS resolve from host: `dig @127.0.0.1 -p 853 <container-name>.vps-network`
    restart: on-failure
    networks:
      vps-network:
      dns-network:
        ipv4_address: 10.5.0.5

  db:
    build:
      dockerfile: docker/db.Dockerfile
      context: .
    image: koh/db-hub
    container_name: vps_db
    ports:
      - "3306:3306"
    volumes:
      - .docker_cache/db_data:/var/lib/mysql
    networks:
      - default

networks:
  vps-network:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
        - gateway: 172.28.0.0
        - ip_range: 172.28.0.0/16

  dns-network:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 10.5.0.0/24
        - gateway: 10.5.0.1
        - ip_range: 10.5.0.0/26

